variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - publish

build:
  only:
    - branches
  except:
    - tags
  stage: build
  script:
    - cd /Users/aaronmills
    - ./runBuild.sh

publish:
  only:
    - branches
  except:
    - tags
  stage: publish
  script:
    - ./gradlew publish
